from dataclasses import dataclass


@dataclass(slots=True)
class TokenUsage:
    """Statistics for token consumption during LLM interactions.

    Attributes:
        prompt_tokens: Tokens sent to the model (input).
        completion_tokens: Tokens generated by the model (output).
        total_tokens: Sum of prompt and completion tokens.
    """

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0

    def add(self, other: "TokenUsage") -> "TokenUsage":
        """Combine this usage with another and return a new instance.

        Args:
            other: The usage data to add to the current instance.

        Returns:
            A new TokenUsage object containing the sum of both stats.
        """
        return TokenUsage(
            prompt_tokens=self.prompt_tokens + other.prompt_tokens,
            completion_tokens=self.completion_tokens + other.completion_tokens,
            total_tokens=self.total_tokens + other.total_tokens,
        )
