from collections.abc import AsyncIterator
from typing import Any, cast

from openai import AsyncOpenAI, pydantic_function_tool

from copilot_orchestrator.domain.entities.message import AgentMessage
from copilot_orchestrator.domain.enums.message_role import MessageRole
from copilot_orchestrator.domain.ports.llm_provider import LLMProvider


class OpenAIClient(LLMProvider):
    """Infrastructure adapter for OpenAI Chat Completions API.

    This client implements the LLMProvider port, translating between
    domain entities and the OpenAI SDK format.
    """

    def __init__(self, async_client: AsyncOpenAI, model: str = "gpt-4o-mini"):
        """Initialize the client with an authenticated AsyncOpenAI instance.

        Args:
            async_client: Pre-configured OpenAI client.
            model: The model identifier to use for generations.
        """
        self._client = async_client
        self._model = model

    async def generate(
        self, messages: list[AgentMessage], tools: list[type] | None = None
    ) -> AgentMessage:
        """Generate a chat completion using the OpenAI Chat Completions API.

        Translates domain AgentMessage entities to the OpenAI-native message
        schema before execution.

        Args:
            messages: Full conversation history to send to the model.
            tools: Optional list of Pydantic models to use as tools.

        Returns:
            A new AgentMessage containing the model's textual response or tool calls.
        """
        openai_messages = []
        for msg in messages:
            open_msg: dict[str, Any] = {
                "role": msg.role.value,
                "content": msg.content,
            }
            if msg.name:
                open_msg["name"] = msg.name
            if msg.tool_calls:
                open_msg["tool_calls"] = msg.tool_calls
            if msg.tool_call_id:
                open_msg["tool_call_id"] = msg.tool_call_id

            openai_messages.append(open_msg)

        # Map tools if provided
        openai_tools = None
        if tools:
            openai_tools = [
                pydantic_function_tool(t, name=getattr(t, "model_config", {}).get("title"))
                for t in tools
            ]

        # Call the provider
        kwargs: dict[str, Any] = {
            "model": self._model,
            "messages": cast(Any, openai_messages),
            "temperature": 0,
        }
        if openai_tools:
            kwargs["tools"] = openai_tools

        response = await self._client.chat.completions.create(**kwargs)

        # Map back to domain
        message = response.choices[0].message
        content = message.content or ""
        tool_calls = [tc.model_dump() for tc in message.tool_calls] if message.tool_calls else []
        usage = response.usage.model_dump() if response.usage else {}

        return AgentMessage(
            role=MessageRole.ASSISTANT,
            content=content,
            tool_calls=tool_calls,
            metadata={"model": self._model, "usage": usage},
        )

    async def generate_structured(self, messages: list[AgentMessage], response_model: type) -> Any:
        """Produce a validated Pydantic object from the model using native parsing.

        Args:
            messages: Full conversation history to send to the model.
            response_model: The Pydantic model class to enforce on the output.

        Returns:
            An instance of the specified response_model containing parsed data.
        """
        openai_messages = []
        for msg in messages:
            open_msg = {
                "role": msg.role.value,
                "content": msg.content,
            }
            if msg.name:
                open_msg["name"] = msg.name
            openai_messages.append(open_msg)

        # Use OpenAI's native Pydantic parsing
        completion = await self._client.beta.chat.completions.parse(
            model=self._model,
            messages=cast(Any, openai_messages),
            response_format=response_model,
        )

        return completion.choices[0].message.parsed

    async def stream(self, messages: list[AgentMessage]) -> AsyncIterator[str]:
        """Stream the chat completion content chunk-by-chunk for real-time responses.

        This method is an async generator that yields content deltas as they are
        received from the OpenAI API.

        Args:
            messages: Full conversation history to send to the model.

        Yields:
            Content chunks (strings) as they are generated by the model.
        """
        openai_messages = []
        for msg in messages:
            open_msg = {
                "role": msg.role.value,
                "content": msg.content,
            }
            if msg.name:
                open_msg["name"] = msg.name
            openai_messages.append(open_msg)

        response = await self._client.chat.completions.create(
            model=self._model,
            messages=cast(Any, openai_messages),
            stream=True,
        )

        async for chunk in response:
            if chunk.choices and chunk.choices[0].delta.content:
                yield chunk.choices[0].delta.content
